Fix compilation with libc++
Build with libc++ (Clang-20, Gentoo LLVM profile) fails due to transitive include with:
```
s_Sys.cpp.o -c ../hyprland-source/hyprpm/src/helpers/Sys.cpp
../hyprland-source/hyprpm/src/helpers/Sys.cpp:24:24: error: implicit instantiation of undefined template 'std::basic_ostringstream<char>'
   24 |     std::ostringstream oss;
      |                        ^
/usr/include/c++/v1/__fwd/sstream.h:28:28: note: template is declared here
   28 | class _LIBCPP_TEMPLATE_VIS basic_ostringstream;
      |                            ^
1 error generated.
```