helpers: add missing headers
src/helpers/BezierCurve.cpp:62:50: error: no member named 'clamp' in namespace 'std'
    const auto LOWERPOINT = &m_aPointsBaked[std::clamp((int)((float)BAKEDPOINTS * lowerT), 0, 199)];
                                            ~~~~~^
src/helpers/BezierCurve.cpp:63:50: error: no member named 'clamp' in namespace 'std'
    const auto UPPERPOINT = &m_aPointsBaked[std::clamp((int)((float)BAKEDPOINTS * upperT), 0, 199)];
                                            ~~~~~^
src/hyprerror/../defines.hpp:58:9: note: expanded from macro 'RASSERT'
        *((int*)nullptr) = 1; /* so that we crash and get a coredump */                                                                                                            \
        ^
src/helpers/MiscFunctions.cpp:173:24: error: implicit instantiation of undefined template 'std::basic_ostringstream<char>'
    std::ostringstream oss;
                       ^