hyprctl: add missing header
src/debug/HyprCtl.cpp:86:24: error: implicit instantiation of undefined template 'std::basic_ostringstream<char>'
    std::ostringstream result;
                       ^
/usr/include/include/c++/v1/iosfwd:131:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_ostringstream;
                               ^